# Generated by Django 3.1.5 on 2021-02-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210131_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='opening',
            field=models.TextField(null=True),
        ),
    ]
