# Generated by Django 3.1.5 on 2021-02-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
