# Generated by Django 3.1.5 on 2021-02-03 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_comment_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
