# Generated by Django 3.1.5 on 2021-01-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210129_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surflesson',
            options={'verbose_name': 'Surf Lesson'},
        ),
    ]
