# Generated by Django 3.1.5 on 2021-02-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210130_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurfLesson',
        ),
    ]
